name: Check Commit Messages
on:
  pull_request:

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Not Squashable
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^(?!(fixup|squash)! )"
          error: "You cannot merge squash commits."
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Commit Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^[^#].{0,74}$"
          error: "The maximum commit line length of 74 characters is exceeded."
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Pull Request Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\\[[^\\]]+\\] .+$'
          error: 'Your pull request title must contain a type like "[BUGFIX]".'
          excludeDescription: true
